#!/usr/bin/env python

import sys, re

message = open(sys.argv[1],'r').read().strip()

checker = re.compile(r"[A-Z\d]+-{1}[0-9]+:.*")

if checker.match(message):
	print "Commit message checker: OK"
	exit(0)
else:
	print "Commit message checker: FAIL"
	print '"{}" does not include issue tracker code.'.format(message)
	print 'Expected format: "{project}-{number}: {commit description}"'
