#!/usr/bin/env bash

commit_regex='([A-Z\d]*-[0-9]+|merge)'
error_msg="ABORTING COMMIT! Missing JIRA Issue ID: $(cat $1)"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi